# Generated by Django 4.2.24 on 2025-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
